declare module 'react-native-spotify-web-api';
declare module 'js-cookie';
declare module 'react-spotify-auth';
declare module 'react-spotify-api';
declare module 'country-data';
declare module 'react-native-slider';
declare module 'react-native-modal-dropdown';
declare module 'loadash';
declare module '@react-native-community/async-storage';